[project]
name = "face-match-age"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lightning>=2.6.0",
    "matplotlib>=3.10.7",
    "requests>=2.32.5",
    "tensorboard>=2.20.0",
    "torch>=2.9.1",
]
